version: 2
updates:
  - package-ecosystem: docker
    directories:
      - "**/*"
    schedule:
      interval: daily
    ignore:
      - dependency-name: dotnet/sdk
        update-types: ["version-update:semver-major"]
    groups:
      all-docker:
        patterns:
          - "*"
  - package-ecosystem: docker-compose
    directories:
      - "**/*"
    schedule:
      interval: daily
    ignore:
      - dependency-name: localhost
      - dependency-name: dotnet/sdk
        update-types: ["version-update:semver-major"]
    groups:
      all-docker-compose:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directories:
      - /
      - "**/*"
    schedule:
      interval: daily
    groups:
      all-github-actions:
        patterns:
          - "*"

  - package-ecosystem: nuget
    directories:
      # Dependabot can't update this project because it uses a custom package registry
      #- /tests/custom-package-registry-test/TestProject.UnitTests/
      - /tests/sample-projects/basic/TestProject.UnitTests/
      - /tests/sample-projects/broken-compile/TestProject.UnitTests/
      - /tests/sample-projects/different-naming-pattern/TestProject.Tests/
      - /tests/sample-projects/failing-tests/TestProject.UnitTests/
      - /tests/sample-projects/half-covered/TestProject.UnitTests/
      - /tests/sample-projects/missing-coverage-collector/TestProject.UnitTests/
      - /tests/sample-projects/multiple/AnotherProject.UnitTests/
      - /tests/sample-projects/multiple/TestProject.UnitTests/
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: PublishProject # Local test project published to local test package registry
    groups:
      nuget-minor-patch:
        patterns:
          - "*"
