services:
  actions-test-dotnet-dev:
    container_name: actions-test-dotnet-dev
    image: docker.io/spritelydev/dotnet10-devcontainer:0.1.1@sha256:c068a0c842f173ab7934a410fbd823ee63e6e8faf3cf689dcf6186f56b05e313
    privileged: true
    command: /bin/sh -c "sleep infinity"
    volumes:
      - ../:/src
      - ${HOME:-$USERPROFILE}/.ssh:/root/.ssh:ro
    env_file:
      - .env
    # Environment variables have higher precedence than the .env file
    environment:
      - NUGET_TOKEN=${NUGET_TOKEN}
