services:
  actions-test-dotnet-dev:
    container_name: actions-test-dotnet-dev
    image: docker.io/spritelydev/dotnet8-devcontainer:0.2.8
    command: /bin/sh -c "sleep infinity"
    volumes:
      - ../:/src
      - ${HOME:-$USERPROFILE}/.ssh:/root/.ssh:ro
    env_file:
      - .env
