services:
  actions-test-dotnet-dev:
    container_name: actions-test-dotnet-dev
    build:
      dockerfile: Dockerfile
    command: /bin/sh -c "sleep infinity"
    volumes:
      - ../:/src
      - ${HOME:-$USERPROFILE}/.ssh:/root/.ssh:ro
    env_file:
      - .env
